name: flutter_shop_practice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  provider: ^5.0.0
  persistent_bottom_nav_bar: ^4.0.2
  flutter_spinkit: ^5.0.0
  lottie: ^1.0.1
  shared_preferences: ^2.0.6
  image_picker: ^0.8.2
  multi_image_picker2: ^5.0.2
  http_parser: ^4.0.0
  path: ^1.8.0
  sqflite: ^2.0.0+3
  flutter_share: ^2.0.0
  url_launcher: ^6.0.9
  connectivity: ^3.0.6
  awesome_dialog: ^2.1.0




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - splash.json
    - wait.json
    - logins.png
    - spin.gif
    - signups.png
    - welcome.png
    - play.png
    - box.png
    - connect.png
    - camera.png
    - icon1.png
    - icon2.png
    - icon3.png
    - icon4.png
    - icon5.png
    #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: bold
      fonts:
        - asset: fonts/bold.ttf

    - family: light
      fonts:
        - asset: fonts/light.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
